### ISSUE TITLE
Names are not colored properly upon loggin!

### ISSUE THREAD

**Issue by Scottss** [ironbane/IronbaneServerLegacy#180] opened 2013-08-27 11:44 UTC
Current online players list is not colored properly. Along with the players name that is currently logged in.

**Comment by nickjanssen** [comment] 2013-08-27 14:04
Ooohhh, I thought you had a pull request ready ;) duplicate of #173

**Closed as completed by nickjanssen** 2013-08-27 14:04 UTC

**Comment by Scottss** [comment] 2013-08-27 21:47
Ohh.. sorry brooo! Ill get on that xD
