### ISSUE TITLE
Terrain auto-smooths after next login

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#177] opened 2013-08-25 03:00 UTC
When I uploaded the new map, the terrain was jagged, pointy, pixel-ated and all that. When I re-logged (I think that's what caused it; to be honest, I wasn't really paying attention), it had all smoother back out again. Will investigate further.

**Comment by nickjanssen** [comment] 2013-08-25 09:07
probably duplicate of #93 ?

**Comment by samjar** [comment] 2013-08-25 20:24
Yup! Sorry, didn't know there was one of these already haha

**Comment by nickjanssen** [comment] 2013-08-26 13:05
No worries :) You can search issues using the searchbar at the top

**Closed as completed by nickjanssen** 2013-08-26 13:05 UTC
Labels: bug
