### ISSUE TITLE
Banks

### ISSUE THREAD

**Issue by TheRestIsATest** [ironbane/IronbaneServerLegacy#287] opened 2013-11-05 12:52 UTC
People are desperately asking for banks or a larger inventory. When are we going to work on it?

**Comment by lschans** [comment] 2013-11-05 14:41
Dont know, I do know that Kevin had a good idea for this.

On Tue, Nov 5, 2013 at 1:52 PM, Meanapple notifications@github.com wrote:

> People are desperately asking for banks or a larger inventory. When are we
> going to work on it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/287
> .

## 

---

Lars van der Schans

**Comment by bsparks** [comment] 2013-11-05 22:31
duplicate of issue #37

**Closed as completed by bsparks** 2013-11-05 22:31 UTC
